# Generated by Django 2.1.4 on 2018-12-17 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_content',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
