# Generated by Django 2.1.4 on 2018-12-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateField(verbose_name='期日'),
        ),
        migrations.AlterField(
            model_name='list',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='ランク'),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
    ]
