# Generated by Django 2.1.4 on 2018-12-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20181211_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='list',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
