# Generated by Django 2.1.4 on 2018-12-12 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_list_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='origin',
            field=models.ImageField(default=1, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 12, 17, 40, 22, 636218)),
        ),
    ]
