# Generated by Django 2.1.4 on 2018-12-13 05:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20181213_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 14, 23, 7, 466199)),
        ),
        migrations.AlterField(
            model_name='list',
            name='origin',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg'])], verbose_name='イメージファイル'),
        ),
    ]
