# Generated by Django 2.1.4 on 2018-12-13 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_auto_20181213_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 14, 33, 19, 708699)),
        ),
        migrations.AlterField(
            model_name='list',
            name='origin',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
