# Generated by Django 2.1.4 on 2018-12-13 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_auto_20181213_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='origin',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 15, 4, 55, 90017)),
        ),
    ]
