# Generated by Django 2.1.4 on 2018-12-13 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_auto_20181213_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 15, 37, 30, 350628)),
        ),
    ]
