# Generated by Django 2.1.4 on 2018-12-13 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_auto_20181213_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 16, 15, 55, 104403)),
        ),
    ]
