# Generated by Django 2.1.4 on 2018-12-14 01:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0014_auto_20181213_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 12, 14, 10, 21, 44, 672607))),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 14, 10, 21, 44, 671386)),
        ),
        migrations.AlterModelTable(
            name='list',
            table='list',
        ),
        migrations.AddField(
            model_name='comment',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.List'),
        ),
    ]
